// Samples with Grid/Angular Modules Grid sample/src/app/master-view/master-view.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { IGridRowEventArgs, IgxDialogComponent, IgxGridComponent } from '@infragistics/igniteui-angular';
import { NorthwindService } from '../services/northwind.service';

@Component({
  selector: 'app-master-view',
  templateUrl: './master-view.component.html',
  styleUrls: ['./master-view.component.scss']
})
export class MasterViewComponent implements OnInit {
  @ViewChild('grid', { read: IgxGridComponent, static: true }) public grid: IgxGridComponent;
  @ViewChild('form', { read: IgxDialogComponent, static: true }) public dialog: IgxDialogComponent;
  public northwindCustomers: any[] = [];
  public customer: ReturnType<MasterViewComponent['createCustomerForm']>;
  public errorMessage: string = '';
  public dialogTitle: string = '';
  public confirmText: string = '';
  public confirmEvent: string = '';
  public isDeleteButtonHidden: boolean = false;
  private originalCustomer: any | null = null;

  constructor(private northwindService: NorthwindService) {
    this.customer = this.createCustomerForm();
  }

  ngOnInit() {
    this.fetchCustomers();
  }

  private createCustomerForm() {
    return new FormGroup({
      customerId: new FormControl<string | null>(null),
      companyName: new FormControl<string | null>(null, Validators.required),
      contactName: new FormControl<string | null>(null, Validators.pattern("^[a-zA-Z]+( [a-zA-Z]+)*$")),
      contactTitle: new FormControl<string | null>(null, Validators.required),
      address: new FormGroup({
        street: new FormControl<string | null>(null, Validators.required),
        city: new FormControl<string | null>(null, Validators.required),
        region: new FormControl<string | null>(null, Validators.required),
        postalCode: new FormControl<string | null>(null, Validators.required),
        country: new FormControl<string | null>(null, Validators.required),
        phone: new FormControl<string | null>(null, Validators.required)
      })
    });
  }

  private fetchCustomers(): void {
    this.northwindService.getCustomers().subscribe({
      next: (data) => this.northwindCustomers = data,
      error: () => this.northwindCustomers = []
    });
  }

  public handleRowSelection(event: IGridRowEventArgs): void {
    if (event.row.data) {
      this.originalCustomer = JSON.parse(JSON.stringify(event.row.data));
      this.customer.patchValue(event.row.data);
      this.dialogTitle = 'Edit customer';
      this.confirmText = 'Edit customer';
      this.confirmEvent = 'onEditCustomer';
      this.dialog.open();
    }
  }

  public resetCustomer(): void {
    if (this.originalCustomer) {
      this.customer.patchValue(this.originalCustomer);
      this.errorMessage = '';
    }
  }

  public resetHandler(): void {
    if (this.confirmText === 'Add customer') {
      this.resetForm();
    } else if (this.confirmText === 'Edit customer') {
      this.resetCustomer();
    }
  }

  public onFormOpen(): void {
    this.customer.reset();
    this.dialogTitle = 'Add new customer';
    this.confirmText = 'Add customer';
    this.confirmEvent = 'onAddNewCustomer';
    this.isDeleteButtonHidden = true;
    this.dialog.open();
  }

  private resetForm(): void {
    this.customer.reset();
    this.errorMessage = '';
  }

  private handleResponse(response: any): void {
    this.fetchCustomers(); // Update customer list
    this.resetForm();
    this.dialog.close();
  }

  private handleError(error: any): void {
    if (error.error) {
      this.errorMessage = Object.values(error.error).join('\n');
    } else {
      this.errorMessage = error.message || 'An error occurred.';
    }
  }

  public onEditCustomer(): void {
    if (this.customer.valid) {
      const updatedCustomer = this.customer.getRawValue();
      this.northwindService.updateCustomer(updatedCustomer).subscribe({
        next: (response) => this.handleResponse(response),
        error: (error) => this.handleError(error)
      });
    } else {
      this.errorMessage = 'Please provide valid data for all fields.';
    }
  }

  public onAddNewCustomer(): void {
    if (this.customer.valid) {
      const newCustomer = this.customer.getRawValue();
      this.northwindService.addCustomer(newCustomer).subscribe({
        next: (response) => this.handleResponse(response),
        error: (error) => this.handleError(error)
      });
    } else {
      this.errorMessage = 'Please provide valid data for all fields.';
    }
  }

  public onDelete(): void {
    const myCustomerId = this.customer.value.customerId;
    if (myCustomerId) {
      this.northwindService.deleteCustomer(myCustomerId).subscribe({
        next: (response) => this.handleResponse(response),
        error: (error) => this.handleError(error)
      });
    } else {
      this.errorMessage = 'Please provide valid data for all fields.';
    }
  }

  public onConfirm(): void {
    if (this.confirmText === 'Add customer') {
      this.onAddNewCustomer();
    } else if (this.confirmText === 'Edit customer') {
      this.onEditCustomer();
    }
  }

  public onDialogClosed(): void {
    this.isDeleteButtonHidden = false;
  }
}

<div class="column-layout group">
  <igx-grid #grid primaryKey="customerId" displayDensity="cosy" rowSelection="single" [hideRowSelectors]="true"
    [data]="northwindCustomers" class="grid" (rowClick)="handleRowSelection($event)">
    <igx-column field="customerId" dataType="string" header="customerId" [filterable]="false"
      [selectable]="false"></igx-column>
    <igx-column field="companyName" dataType="string" header="companyName" [filterable]="false"
      [selectable]="false"></igx-column>
    <igx-column field="contactName" dataType="string" header="contactName" [filterable]="false"
      [selectable]="false"></igx-column>
    <igx-column field="contactTitle" dataType="string" header="contactTitle" [filterable]="false"
      [selectable]="false"></igx-column>
      <igx-column field="address.region" dataType="string" header="address region" [filterable]="false"
      [selectable]="false"></igx-column>
    <igx-column field="address.city" dataType="string" header="address city" [filterable]="false"
      [selectable]="false"></igx-column>
    <igx-column field="address.street" dataType="string" header="address street" [filterable]="false"
      [selectable]="false"></igx-column>
    <igx-column field="address.postalCode" dataType="string" header="address postal code" [filterable]="false"
      [selectable]="false"></igx-column>
    <igx-column field="address.country" dataType="string" header="address country" [filterable]="false"
      [selectable]="false"></igx-column>
    <igx-column field="address.phone" dataType="string" header="address phone" [filterable]="false"
      [selectable]="false"></igx-column>
  </igx-grid>
  <button igxButton="contained" igxRipple="white" (click)="onFormOpen()">Add new customer</button>
  <igx-dialog #form [closeOnOutsideSelect]="true" (closed)="onDialogClosed()">
    <igx-dialog-title>
      <div class="title-container">
        <div class="dialog-title">{{ dialogTitle }}</div>
      </div>
    </igx-dialog-title>

    <form class="input-group-form" [formGroup]="customer" (ngSubmit)="onAddNewCustomer()">
      <div class="column-layout group">
        <igx-input-group type="border" class="ig-typography__body-1 textarea">
          <input name="customerId" type="text" formControlName="customerId" igxInput />
          <label igxLabel for="customerId">Customer ID</label>
        </igx-input-group>
        <igx-input-group type="border" class="ig-typography__body-1 textarea">
          <input name="companyName" type="text" formControlName="companyName" igxInput />
          <label igxLabel for="companyName">Company Name</label>
        </igx-input-group>
        <igx-input-group type="border" class="ig-typography__body-1 textarea">
          <input name="contactName" type="text" formControlName="contactName" igxInput />
          <label igxLabel for="contactName">Contact Name</label>
        </igx-input-group>
        <igx-input-group type="border" class="ig-typography__body-1 textarea">
          <input name="contactTitle" type="text" formControlName="contactTitle" igxInput />
          <label igxLabel for="contactTitle">Contact Title</label>
        </igx-input-group>
        <div [formGroup]="customer.controls.address">
          <igx-input-group type="border" class="ig-typography__body-1 textarea">
            <input name="region" type="text" formControlName="region" igxInput />
            <label igxLabel for="region">Region</label>
          </igx-input-group>
          <igx-input-group type="border" class="ig-typography__body-1 textarea">
            <input name="city" type="text" formControlName="city" igxInput />
            <label igxLabel for="city">City</label>
          </igx-input-group>
          <igx-input-group type="border" class="ig-typography__body-1 textarea">
            <input name="street" type="text" formControlName="street" igxInput />
            <label igxLabel for="street">Street</label>
          </igx-input-group>
          <igx-input-group type="border" class="ig-typography__body-1 textarea">
            <input name="postalCode" type="text" formControlName="postalCode" igxInput />
            <label igxLabel for="postalCode">Postal code</label>
          </igx-input-group>
          <igx-input-group type="border" class="ig-typography__body-1 textarea">
            <input name="country" type="text" formControlName="country" igxInput />
            <label igxLabel for="country">Country</label>
          </igx-input-group>
          <igx-input-group type="border" class="ig-typography__body-1 textarea">
            <input name="phone" type="text" formControlName="phone" igxInput />
            <label igxLabel for="phone">Phone</label>
          </igx-input-group>
        </div>
        <div *ngIf="errorMessage" class="error-message">{{ errorMessage }}</div>
      </div>
    </form>

    <div igxDialogActions>
      <button igxButton class="alert" (click)="onDelete()" [hidden]="isDeleteButtonHidden">Delete customer</button>
      <button igxButton (click)="form.close()">CANCEL</button>
      <button igxButton (click)="resetHandler()">Reset form</button>
      <button igxButton (click)="onConfirm()">{{confirmText}}</button>
    </div>
  </igx-dialog>
</div>

// React Grid sample/src/app/master-view/master-view.tsx
import { IgrButton, IgrButtonModule, IgrDialog, IgrDialogModule, IgrInput, IgrInputModule, IgrTextareaModule } from "@infragistics/igniteui-react";
import { IgrColumn, IgrGrid, IgrGridModule, IgrRowSelectionEventArgs } from '@infragistics/igniteui-react-grids';
import '@infragistics/igniteui-react-grids/grids';
import { useReducer, useRef, useState } from "react";
import { useGetCustomerInputModelList } from '../hooks/north-wind-crud-hooks';
import createClassTransformer from '../style-utils';
import styles from './master-view.module.css';
import { CustomerInputModel } from "../models/NorthWindCRUD/customer-input-model";
import { addCustomer, getCustomerInputModelList, updateCustomer } from "../services/north-wind-crud";

IgrButtonModule.register();
IgrDialogModule.register();
IgrGridModule.register();
IgrInputModule.register();
IgrTextareaModule.register();

export default function MasterView() {
  const classes = createClassTransformer(styles);
  const [customers, setCustomers] = useState<CustomerInputModel[]>([]);
  const { northWindCRUDCustomerInputModel } = useGetCustomerInputModelList();
  const dialogRef = useRef<IgrDialog>(null);
  const [, forceUpdate] = useReducer(x => x + 1, 0);
  const formElement = useRef<HTMLFormElement>(null);
  const [confirmText, setConfirmText] = useState('');
  const [errorMessage, setErrorMessage] = useState('');
  const [selectedCustomer, setSelectedCustomer] = useState(null);

  const next = () => {
    forceUpdate();
  };

  const onDialogShow = () => {
    if (dialogRef.current) {
      dialogRef.current.show();
    }
  };

  const onDialogHide = () => {
    if (dialogRef.current) {
      dialogRef.current.hide();
    }
  };

  const onAddFormOpen = () => {
    //resetForm();
    setConfirmText("Add customer");
    if (dialogRef.current) {
      dialogRef.current.show();
    }
  };

  const onAddNewCustomer = () => {
    const formData = new FormData(formElement.current);
    const newCustomer = {
      customerId: formData.get('customerId'),
      companyName: formData.get('companyName'),
      contactName: formData.get('contactName'),
      contactTitle: formData.get('contactTitle'),
      address: {
        city: '',
        country: '',
        street: '',
        region: '',
        postalCode: '',
        phone: ''
      }
    };

    addCustomer(newCustomer).then(handleResponse).catch(handleError);
  };

  const onEditCustomer = () => {
      const formData = new FormData(formElement.current);
      const updatedCustomer = {
        customerId: formData.get('customerId'),
        companyName: formData.get('companyName'),
        contactName: formData.get('contactName'),
        contactTitle: formData.get('contactTitle'),
        address: {
          city: '',
          country: '',
          street: '',
          region: '',
          postalCode: '',
          phone: ''
        }
      };

      updateCustomer(updatedCustomer).then(handleResponse).catch(handleError);
  };

  const onConfirm = () => {
    if (confirmText === 'Add customer') {
      onAddNewCustomer();
    } else if (confirmText === 'Edit customer') {
      onEditCustomer();
    }
  };

  const resetForm = () => {
    formElement.current?.reset();
  };

  const resetCustomer = () => {
    if (selectedCustomer) {
      (formElement.current?.elements.namedItem("companyName") as HTMLInputElement).value = selectedCustomer.companyName;
      (formElement.current?.elements.namedItem("customerId") as HTMLInputElement).value = selectedCustomer.customerId;
      (formElement.current?.elements.namedItem("contactName") as HTMLInputElement).value = selectedCustomer.contactName;
      (formElement.current?.elements.namedItem("contactTitle") as HTMLInputElement).value = selectedCustomer.contactTitle;
    }
  };

  const resetHandler = () => {
    if (confirmText === 'Add customer') {
      resetForm();
    } else if (confirmText === 'Edit customer') {
      resetCustomer();
    }
  };

  const handleResponse = (response) => {
    console.log('Operation successful:', response);
    getCustomerInputModelList().then(setCustomers).catch(console.error);
    onDialogHide();
  };

  const handleError = (error) => {
    console.error('Error:', error);
    setErrorMessage(error.message || 'An error occurred.');
  };

  const renderHelperText = (fieldName) => {
    const field = formElement.current?.elements.namedItem(fieldName);
    if (field && (field as HTMLInputElement).validity.valueMissing) {
      return (
        <span slot="helper-text" className={classes("helper-text")} key={`${fieldName}-helper`}>
          This field is required
        </span>
      );
    }
    return null;
  };

  const handleRowSelection = (owner: IgrGrid, args: IgrRowSelectionEventArgs) => {
    setConfirmText("Edit customer");
    const selectedRow = args.detail.newSelection[0];

    setSelectedCustomer(selectedRow);

    (formElement.current?.elements.namedItem("customerId") as HTMLInputElement).value = selectedRow.customerId;
    (formElement.current?.elements.namedItem("companyName") as HTMLInputElement).value = selectedRow.companyName;
    (formElement.current?.elements.namedItem("contactName") as HTMLInputElement).value = selectedRow.contactName;
    (formElement.current?.elements.namedItem("contactTitle") as HTMLInputElement).value = selectedRow.contactTitle;

    onDialogShow();
  };

  return (
    <>
      <div className={classes("row-layout master-view-container")}>
        <IgrGrid data={northWindCRUDCustomerInputModel} rowSelection="single" rowSelectionChanging={handleRowSelection} primaryKey="customerId" displayDensity="cosy" allowFiltering="true" filterMode="excelStyleFilter" className={classes("ig-typography ig-scrollbar grid")}>
          <IgrColumn field="customerId" dataType="string" header="customerId" sortable="true" selectable="false" />
          <IgrColumn field="companyName" dataType="string" header="companyName" sortable="true" selectable="false" />
          <IgrColumn field="contactName" dataType="string" header="contactName" sortable="true" selectable="false" />
          <IgrColumn field="contactTitle" dataType="string" header="contactTitle" sortable="true" selectable="false" />
          <IgrColumn field="address.city" dataType="string" header="address city" sortable="true" selectable="false" />
          <IgrColumn field="address.country" dataType="string" header="address country" sortable="true" selectable="false" />
        </IgrGrid>
        <IgrDialog title="Confirmation" ref={dialogRef}>
          <form className="form" ref={formElement}>
            <IgrInput label="Customer ID" outlined="true" name="customerId" className={classes("user-input")} key="customerId" blur={next}>
            </IgrInput>
            <IgrInput label="Company name" outlined="true" name="companyName" className={classes("user-input")} key="companyName" required={true} blur={next}>
              {renderHelperText("companyName")}
            </IgrInput>
            <IgrInput label="Contact name" outlined="true" name="contactName" className={classes("user-input")} key="contactName" required={true} blur={next}>
              {renderHelperText("contactName")}
            </IgrInput>
            <IgrInput label="Contact title" outlined="true" name="contactTitle" className={classes("user-input")} key="contactTitle" required={true} blur={next}>
              {renderHelperText("contactTitle")}
            </IgrInput>
          </form>
          <div slot="footer">
            <IgrButton clicked={onDialogHide} variant="flat"><span>Cancel</span></IgrButton>
            <IgrButton clicked={resetHandler} variant="flat"><span>Reset form</span></IgrButton>
            <IgrButton clicked={onConfirm} variant="flat"><span>{confirmText}</span></IgrButton>
          </div>
        </IgrDialog>
        <IgrButton variant="contained" clicked={onAddFormOpen}>
          <span>Add customer</span>
        </IgrButton>
      </div>
    </>
  );
}
